@WebApi_HostAddress = http://localhost:5243

GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

### Zoe Koval
GET {{WebApi_HostAddress}}/api/contacts/a98f3383-0bf9-4e96-9b6f-cfbf2f4906af
Accept: application/json

### Mike Schmidt
GET {{WebApi_HostAddress}}/api/contacts/fd3857b4-3c82-4010-8800-cbdbaaa93351
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Albert",
  "lastName" : "Coval",
  "Email": "Albert@wsei.edu.pl",
  "phone": "+48451514165"
}

### Albert Coval (if created)
GET {{WebApi_HostAddress}}/api/contacts/49592f29-ed9a-4d23-a826-8835504a04c3
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Albert",
  "lastName" : "Coval"
}

###

POST {{WebApi_HostAddress}}/api/contacts/49592f29-ed9a-4d23-a826-8835504a04c3/notes
Content-Type: application/json

{
  "content": "IT'S ME",
  "CreatedBy": "Admin"
}

###
GET {{WebApi_HostAddress}}/api/contacts/3d54091d-abc8-49ec-9590-93ad3ed5458f/notes
Content-Type: application/json

###