@WebApi_HostAddress = http://localhost:5243

GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

### Zoe Koval
GET {{WebApi_HostAddress}}/api/contacts/a98f3383-0bf9-4e96-9b6f-cfbf2f4906af
Accept: application/json

### Mike Schmidt
GET {{WebApi_HostAddress}}/api/contacts/fd3857b4-3c82-4010-8800-cbdbaaa93351
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Albert",
  "lastName" : "Coval",
  "Email": "Albert@wsei.edu.pl",
  "phone": "+48451514165"
}

### Albert Coval (if created)
GET {{WebApi_HostAddress}}/api/contacts/0aad2f2c-891d-42a8-8081-af97ac7ae1ff
Accept: application/json

###
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Albert",
  "lastName" : "Coval"
}

###
POST {{WebApi_HostAddress}}/api/contacts/0aad2f2c-891d-42a8-8081-af97ac7ae1ff/notes
Content-Type: application/json

{
  "content": "IT'S ME",
  "CreatedBy": "Admin"
}

###
GET {{WebApi_HostAddress}}/api/contacts/0aad2f2c-891d-42a8-8081-af97ac7ae1ff/notes
Content-Type: application/json

###
DELETE {{WebApi_HostAddress}}/api/contacts/0aad2f2c-891d-42a8-8081-af97ac7ae1ff/notes/dd52b613-41cb-4ef9-a9aa-8924ef8301c0
Content-Type: application/json

###